[supervisord]
user=root
nodaemon=true
logfile=/dev/null
logfile_maxbytes=0
pidfile=/run/supervisord.pid

[program:php-frontend]
directory=/app/service
command=php -S 0.0.0.0:8000
autostart=true
user=root
priority=1000
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:db-initializer]
directory=/app/internal
command=python3 init_db.py
autostart=true
autorestart=false
user=root
priority=1001
startsecs=0

[program:flask-backend]
directory=/app/internal
command=python3 app.py
autostart=true
user=root
priority=1002
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0


